---
title: "TP NGS"
author: Quentin B
date: 15/12/2021
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analyse R - Genome Elimination *M.belari*


### Building of metadata table

```{r coldata}
library(tidyverse)

sampleTable = read_delim("metadata_samples.tsv") %>% as.data.frame()
rownames(sampleTable) = sampleTable$sample_ID
sampleTable

```


### Data import

```{r tximport}

library(tximport)

dir <- "/home/rstudio/mydatalocal/tp_illumination_qb/results/quantification/"
samples <- list.dirs(dir, full.names = F) 
samples <- samples[samples != ""] # remove "." directory

samples_names <- rownames(sampleTable)

files <- file.path(dir, samples_names, "abundance.h5")
names(files) <- samples_names
files[!file.exists(files)]

txi.kallisto.tmp <- tximport(files[1], type = "kallisto", txOut = TRUE)

transcript_names <- rownames(txi.kallisto.tmp$abundance)
tx2gene <- data.frame(tx=transcript_names,
                  gene=gsub(".t[0-9]*","",transcript_names))
txi.kallisto <- tximport(files, type = "kallisto", tx2gene = tx2gene)

```


### Building the DESeq2 object

```{r DESeq2}

library(DESeq2)

dds <- DESeqDataSetFromTximport(txi.kallisto, sampleTable, ~ elimination )
dds <- DESeq(dds)
vsd <- vst(dds, blind=FALSE)

```


### Principal component analysis (PCA)

```{r PCA}

plotPCA(vsd, intgroup=c("age"))

```

```{r res}

res <- results(dds)

```

### MA-plot

```{r}

resultsNames(dds)

```


```{r MA-plot}

plotMA(res, ylim=c(-28,28))

```

### Upregulated genes during eliminations identification

Creation of a dataframe from res matrix.
```{r dataframe}

res_df <- as.data.frame(res)
head(res_df)

```

Identification of the most upregulated genes during elimination:
```{r}

subset(res_df, log2FoldChange > 20 & baseMean > 10 & padj < 0.05)

```

```{r}
summary(res)
```

